name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  pull_request:
    branches:
      - master
      - develop
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: subdir/package-lock.json
      - name: Install
        run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          # github_token: ${{ secrets.TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
      - name: check lint
        run: yarn lint

# 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
