name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
      - run: yarn lint

# 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
